almacenwms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import RedirectView
from wms import views


admin.site.site_header = "WMS Oasis"
admin.site.site_title = "WMS Admin Portal"
admin.site.index_title = "Bienvenido a WMS Oasis"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('almacen/',include('wms.urls')),
    path('',views.index),
#    path('select2/', include('django_select2.urls')),




]

wms/urls.py
from django.contrib import admin
from django.urls import path,include
from wms.views import carga,index,recuperamov,asigna,ubica,productos,asignacionAutomatica,moverproducto,pedidos,creaPedido,\
    VaciaUbicacion,DetalleUbicacion,vacia,estructura,Desglosa,\
    UnidadesxPresentacionPopUp,MoverSeleccion,\
    undadesxpresentacion_query,ubicacionxpresentacion_query,conversioncantidad,verPedido,editaPedido,cancelaPedido,procesarPedido
#,Movimientos,CrearMovimiento,MovimientoDetail,
#PresentacionAutocomplete,UnidadAutocomplete,UbicacionAutocomplete,
#PresentacionxUbicacionAutocomplete,
admin.site.site_header = "WMS Oasis"
admin.site.site_title = "WMS Admin Portal"
admin.site.index_title = "Bienvenido a WMS Oasis"


urlpatterns = [

    path('',estructura,name='Index'),
    path('index/',estructura,name='Index'),
    path('carga/',carga,name='Carga'),
    path('entradas/',carga,name='Entrada'),
    path('salidas/',carga,name='Salida'),
    path('recupera/<idtransa>/<int:tipomov>/',recuperamov,name='Recupera'),

    path('estructura/',estructura,name='Estructura'),
    path('asigna/<idpresentacion>/<idtransa>/<idlinea>/',asigna,name='Asigna'),
    path('mover/<origen>/',MoverSeleccion,name='MoverSel'),

    path('asignaauto/<idtransa>/',asignacionAutomatica,name='AsignaAuto'),
    path('ubica/<idubicacion>/<idlinea>/<int:cantidad>/',ubica,name='Ubica'),
    path('ubican/<idubicacion>/<idlinea>/<int:cantidad>/<int:pale>/',ubica,name='Ubican'),
    path('productos/',productos,name='Productos'),
    path('mover/<idorigen>/<iddestino>/',moverproducto,name='Mover'),
    path('pedidos/',pedidos.as_view(),name='Pedidos'),
    path('pedido/',creaPedido.as_view(),name = 'Pedido'),
    path('verpedido/<int:idpedido>/',verPedido,name = 'VerPedido'),
    path('editapedido/<int:pk>/',editaPedido.as_view(),name = 'EditarPedido'),
    path('procesapedido/<int:pk>/', procesarPedido, name='ProcesaPedido'),
    path('cancelapedido/<int:pk>/', cancelaPedido, name='CancelaPedido'),

    # path('presentacion-autocomplete/',PresentacionAutocomplete.as_view(),name='presentacion-autocomplete'),
    # path('unidades-autocomplete/',UnidadAutocomplete.as_view(),name='unidad-autocomplete'),
    # path('estructura-autocomplete/',UbicacionAutocomplete.as_view(),name='ubicacion-autocomplete'),
    # path('prexubi-autocomplete/',PresentacionxUbicacionAutocomplete.as_view(),name='presentxubicacion-autocomplete'),
    path('vaciar/<int:pk>/',VaciaUbicacion.as_view(),name = 'VaciarUbicacion'),
    path('vacia/<int:pk>/',vacia,name = 'VaciaUbicacion'),
    path('detalleubicacion/<int:pk>/',DetalleUbicacion.as_view(),name = 'DetalleUbicacion'),

    # path('movimientos/',Movimientos.as_view(),name = 'Movimientos'),
    # path('creamovimiento/<int:tipo>/',CrearMovimiento,name = 'CreaMovimiento'),
    # path('creamovimiento/<int:tipo>/<int:pk>/',CrearMovimiento,name = 'AddMovimiento'),
    # path('detallemovimiento/<int:pk>/',MovimientoDetail.as_view(),name = 'DetalleMovimiento'),

    path('desglose/<int:pk>/',Desglosa,name = 'Desglose'),

    path('addundspopup/<presentacionid>/<transaccionid>/<lineaid>/',UnidadesxPresentacionPopUp,name='AddUnidades'),
    path('queryundsxpre/<presentacionid>/<uso>/<int:tipo>/',undadesxpresentacion_query,name='unidadxpre-autocomplete'),
    path('queryubicacion/<presentacionid>/',ubicacionxpresentacion_query,name='presentxubicacion'),
    path('conversion/<presentacionid>/<unidad1>/<unidad2>/<int:cantidad>/',conversioncantidad,name='conversioncantidad'),

]

wms/models.py
from django.db import models
from datetime import date

from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class TipoEstructura(models.Model):
    tipo = models.CharField(max_length=15,verbose_name='Tipo')
    estructurapadre = models.ForeignKey('TipoEstructura', on_delete=models.PROTECT, verbose_name='Estructura padre',null=True,blank=True)
    almacenaje = models.BooleanField(default=False,verbose_name='Permite almacenar')
    zonasalida = models.BooleanField(default=False,verbose_name='Zona de salida de pedidos')
    codificacion = models.CharField(max_length=5,default='')
    orden = models.PositiveIntegerField(default=10)

    def save(self, *args, **kwargs):
        if self.zonasalida and self.almacenaje:
            raise Exception('Puede ser zona de salida o permite almacenar, no los dos al mismo tiempo')
        super(TipoEstructura, self).save(*args, **kwargs)

    def __str__(self):
        return self.tipo


class Almacen(models.Model):
    nombre = models.CharField(max_length=25)
    direccion = models.CharField(max_length=150,null=True,blank=True)
    bloquearconfiguracionestructura = models.BooleanField(default=False)
    pordefecto = models.BooleanField(default=False)

    def save(self, *args, **kwargs):

        if self.pordefecto:
            Almacen.objects.all().exclude(pk=self.pk).update(pordefecto=False)

            super(Almacen,self).save( *args, **kwargs)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural='Almacenes'
        verbose_name = 'Almacen'


class EstructuraAlmacen(models.Model):
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)
    tipoestructura = models.ForeignKey('TipoEstructura', on_delete=models.PROTECT, verbose_name='Tipo estructura')
    alfabetico = models.BooleanField(default=False)
    autonumerar = models.BooleanField(default=False)

    caracteres = models.PositiveIntegerField(default=1)

    codigo = models.CharField(max_length=2,null=True,blank=True)
    cantidad = models.PositiveIntegerField(default=1)
    padre = models.ForeignKey('EstructuraAlmacen', on_delete=models.CASCADE, verbose_name='Estructura padre',null=True,blank=True)

    @property
    def tienehijos(self):
        return TipoEstructura.objects.filter(estructurapadre=self.tipoestructura).exists()

    def __str__(self):
        return '{} - {}'.format(self.tipoestructura,self.cantidad)

    class Meta:
        verbose_name_plural='Configuracion Estructuras Almacen'
        verbose_name = 'Configuracion Estructura Almacen'


class Estructura(models.Model):
    almacen = models.ForeignKey(Almacen,on_delete=models.CASCADE)
    ubicacion = models.CharField(max_length=15,db_index=True,unique=True)
    tipo = models.ForeignKey('TipoEstructura',on_delete=models.PROTECT)
    padre = models.ForeignKey('Estructura',on_delete=models.CASCADE,null=True,blank=True) #limit_choices_to={'tipo__almacenaje':False}
    picking = models.BooleanField(default=False,verbose_name='Picking')
    orden = models.PositiveIntegerField(default=0)
    presentacion = models.ForeignKey('Presentacion', on_delete=models.CASCADE, null=True, blank=True,verbose_name='Presentacion por defecto')

    def raiz(self):
        b = []
        e = self

        while e.padre != None:
            b.append(e.padre.ubicacion)
            e = e.padre

        b.reverse()

        return('/'.join(b))


    #def  save(self, *args, **kwargs):

    #    if self.tipo.almacenaje:
    #       d,created = PresentacionxUbicacion.objects.get_or_create()
    #
    #    super(Estructura, self).save(*args, **kwargs)

    def __str__(self):
        return self.ubicacion

    class Meta:
        verbose_name_plural='Estructuras'
        verbose_name = 'Estructura'


class Unidad(models.Model):
    codigo = models.CharField(max_length=10,primary_key=True,unique=True)
    descripcion = models.CharField(max_length=25)

    def __str__(self):
        return self.codigo

    class Meta:
        verbose_name_plural='Unidad'
        verbose_name = 'Unidades'
        ordering = ('codigo',)


class Grupo(models.Model):
    codigo = models.CharField(max_length=10,primary_key=True)
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name_plural = 'Grupos'
        verbose_name ='Grupo'



class Presentacion(models.Model):
    codigo = models.CharField(max_length=20,primary_key=True)
    descripcion = models.CharField(max_length=100)
    codarticulo = models.CharField(max_length=20, default='', null=True, blank=True)
    grupo = models.ForeignKey('Grupo',on_delete=models.PROTECT, null=True, blank=True)
    unidad = models.ForeignKey(Unidad,on_delete=models.CASCADE,verbose_name='Unidad Base')


    def __str__(self):
        return '{}-{}'.format(self.descripcion,self.codigo)

    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'
        ordering = ['descripcion','codigo']


@receiver(post_save, sender=Presentacion,dispatch_uid='comprueba_unidades')
def comprueba_unidades(sender, instance, **kwargs):
    print(instance)
    if instance.unidad and UnidadesxPresentacion.objects.filter(presentacion=instance,unidad=instance.unidad,uso='B').exists()==False:
        UnidadesxPresentacion(presentacion=instance,unidad = instance.unidad,unidades=1,unidadreferencia= instance.unidad,uso='B').save()


OPCIONESALMACENAMIENTO = (('E','Entrada'),('S','Salida'),('A','Almacenaje'),('B','Base'))

class UnidadesxPresentacion(models.Model):
    presentacion = models.ForeignKey(Presentacion, on_delete=models.CASCADE)
    unidad = models.ForeignKey(Unidad,on_delete=models.PROTECT,db_index=True,verbose_name='Unidad de medida') ## Los id son los nombres de las unidades
    unidades = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='Cantidad en unidad de refencia')
    unidadreferencia = models.ForeignKey(Unidad,on_delete=models.PROTECT,default= '', related_name='unidadref' ,verbose_name='Referente a')
    uso = models.CharField(max_length=1,choices=OPCIONESALMACENAMIENTO)


    class Meta:
        unique_together = ("presentacion","unidadreferencia", "uso")
        verbose_name='Unidad x Presentacion'
        verbose_name_plural = 'Unidades x Presentacion'

    def save(self, *args, **kwargs):
        if self.unidad and not self.unidadreferencia:
            pr=Presentacion.objects.get(codigo=self.presentacion.codigo)
            self.unidadreferencia = pr.unidad
        super(UnidadesxPresentacion, self).save(*args, **kwargs)

    def __str__(self):
        return self.unidad.codigo



class PresentacionxUbicacion(models.Model):
    almacen = models.ForeignKey(Almacen, on_delete=models.PROTECT)
    ubicacion = models.ForeignKey(Estructura,on_delete=models.CASCADE)
    presentacion = models.ForeignKey(Presentacion,on_delete=models.CASCADE,null=True,blank=True)
    fecha = models.DateField(auto_now_add=True,null=True)
    unidad = models.ForeignKey(Unidad, on_delete=models.PROTECT,verbose_name='Unidade de medida')
    stock = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    unidades = models.DecimalField(max_digits=12, decimal_places=4, default=1.0,verbose_name='Piezas en unidad de medida')
    costo = models.DecimalField(max_digits=15, decimal_places=4,default=0)

    def __str__(self):
        return '{}'.format(self.ubicacion)

    class Meta:
        verbose_name = 'Productos x Ubicacion'
        verbose_name_plural = 'Productos x Ubicacion'

class CabeceraPendienteManager(models.Manager):
    def pendientes(self):
        d = EntradaDetalle.objects.filter(transaccion=self, ubicacion__isnull=True).values(
            'transaccion_documento').distinct().exists()
        return d

class EntradaCabecera(models.Model):
    transaccion = models.CharField(max_length=15,db_index=True)
    fecha = models.DateField()
    tipo = models.CharField(max_length=10)
    proveedor = models.CharField(max_length=15)
    documento = models.CharField(max_length=15)
    almaorigen = models.CharField(max_length=15,verbose_name='Almacen Origen',null=True,blank=True)
    almadest = models.CharField(max_length=15,verbose_name='Almacen Destino',null=True,blank=True)
    moneda = models.CharField(max_length=3)
    importe = models.DecimalField(max_digits=15,decimal_places=2,default=0)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    impuestos = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    total = models.DecimalField(max_digits=15, decimal_places=2,default=0)

    asignada = models.BooleanField(default=False)
    fechaasignacion = models.DateTimeField(null=True,blank=True)


    def pendientes(self):
        d = EntradaDetalle.objects.filter(transaccion=self, ubicacion__isnull=True).values('transaccion_documento').distinct().exists()
        return d

    def __str__(self):
        return '{} - {} - {}'.format(self.transaccion,self.fecha,self.proveedor)


class EntradaDetalle(models.Model):
    transaccion = models.ForeignKey(EntradaCabecera,on_delete=models.CASCADE)
    linea = models.PositiveIntegerField()
    presentacion = models.ForeignKey(Presentacion,on_delete=models.PROTECT)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    cantidadxasignar = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    costo = models.DecimalField(max_digits=15, decimal_places=4,default=0)
    importe = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    impuestos = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    total = models.DecimalField(max_digits=15, decimal_places=2,default=0)
    unidad = models.ForeignKey(Unidad,on_delete=models.DO_NOTHING,blank=True,null=True)
    ubicacion = models.CharField(max_length=15,null=True,blank=True)

templates/almacen/asignacion.html
{% extends '../base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block title %}Asignacion{% endblock %}

{%  if request.session.descripcion != '' %}
    {% block breadcrumb %}
            {% if picking %}
                <li class="breadcrumb-item">Mover</li>
            {% else %}
                <li class="breadcrumb-item">Asignacion</li>
            {% endif %}
            <li class="breadcrumb-item active">{{ request.session.descripcion }}</li>
    {% endblock %}
{% endif %}

{% block content %}
    <div class="row m-4">
    {% for estructura in estructuras %}




        <div class="col-1 m-2 border border-dark rounded ubicacion"  id="{{ estructura.id }}">

        <div><h4>{{ estructura.ubicacion }}</h4></div>
            <div><h6>{{ estructura.raiz }}</h6></div>
            {% if estructura.picking %}
                <div class="text text-info"><h6>Picking</h6></div>
            {% endif %}


        </div>

    {% endfor %}
  </div>





<div class="row m-4">

{% if estructuras.has_other_pages %}
    <nav aria-label="Page Navigation">
        <ul class="pagination">
            {% if estructuras.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ estructuras.previous_page_number }}"> Anterior </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Anterior</a>

            {% endif %}

            {% for i in estructuras.paginator.page_range %}
                {% if estructuras.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>

                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if estructuras.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ estructuras.next_page_number }}">Siguiente</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link" href="#">Siguiente</span></li>
            {% endif %}
      </ul>
    </nav>
{% endif %}


</div>

<div class="modal" tabindex="-1" role="dialog" id="preguntacantidad">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Unidades</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

          <p>{{ linea.presentacion }}</p>
          {% if maximo > 0 %}
          <p>Maximo numero de unidades: {{ maximo }} </p>
          {% else %}
          <p>Defina el numero de {{ linea.unidad}}{{maximo|pluralize }} por palé</p>
          {% endif %}
          <form>
            <div class="form-group">

                <label for="cantidadunidades">Cantidad de {{ linea.unidad }}{{maximo|pluralize }} ({{ pale}}) por palé </label>

                {% if maximo == 0 %}
                    <input type="number" class="form-control text-left pull-left"  id="cantidadunidades" min="1" value="1">
                {% else %}
                    <input type="number" class="form-control text-left pull-right" id="cantidadunidades" min="1" max="{{ maximo }}" value={{ maximo }}>
                {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="botonasigna">Asignar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>



<script>
var ubi = '';
$("#cantidadunidades").val({{ maximo }})

$(".ubicacion").click(function () {
    ubi = $(this).attr('id');

    {% if maximo > 0 %}
        vurl = location.origin + '/almacen/ubica/' + ubi + '/'+{{ linea.pk }}+'/{{ maximo|floatformat:"0" }}/';
        console.log(vurl);
        window.location.href = vurl;
    {% else %}
        {$('#preguntacantidad').modal('toggle');}
    {% endif %}

})


$("#botonasigna").click(function(){

    var cantidad = $("#cantidadunidades").val();

    if ({{ maximo }} == 0) {
        vurl = location.origin + '/almacen/ubican/' + ubi + '/'+{{ linea.pk }}+
        '/' + cantidad + '/1/';
        console.log(vurl);
        window.location.href = vurl;
    }

    if ({{maximo}}>0 && cantidad <= {{ maximo }}) {
        vurl = location.origin + '/almacen/ubican/' + ubi + '/'+{{ linea.pk }}+
        '/' + cantidad + '/0/';
        console.log(vurl);
        window.location.href = vurl;
    } else {
        alert('Cantidad maxima a asignar superada');
    }

})

</script>

{% endblock %}

templates/almacen/deatalleubicacion.html
{% load staticfiles %}
<div class="row">
    <div class="col-lg-12 text-left">
        <p><h4 class="text-dark">Descripcion: {{ presentacion.presentacion.descripcion }}  {% if presentacion.ubicacion.picking  %}<img src="{% static '/images/picking.png'%}" alt="Zona Picking" >{% endif %}</h4></p>
        <p></p><h5 class="text-dark">Ubicacion: {{ presentacion.ubicacion.ubicacion }}</h5></p>
        <p>Fecha entrada: {{ presentacion.fecha }}</p>

        Existen {{ presentacion.stock }} {{ presentacion.unidad}}{{presentacion.stock|pluralize }} de {{ presentacion.unidades|floatformat:0 }} unidades con un costo de {% multiplicar presentacion.unidades presentacion.stock presentacion.costo%}




    </div>
</div>

<div class="row">
    <div class="col-lg-12 text-right">


        <a class="btn btn-warning" href="#close" rel="modal:close">Cerrar</a>

    </div>
</div>

templates/almacen/estructura1.html
{% extends '../base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block title %}Estructura{% endblock %}

{%  if request.session.descripcion != '' %}
    {% block breadcrumb %}
            <li class="breadcrumb-item">Asignacion</li>
            <li class="breadcrumb-item active">{{ request.session.descripcion }}</li>
    {% endblock %}
{% endif %}

{% block content %}
sssssssssssssssssssssssss
        <div class="row m-4">
            <h2>
            <a href="{% if  estructuras.first.padre.padre.id == None %} {% url 'EstructuraI'%} {% else %} {% url 'Estructura' estructuras.first.padre.padre.id|unlocalize%} {% endif %}">{{ estructuras.first.padre.ubicacion }} </a>
            </h2>
        </div>
    <div class="row m-4">


    {% for estructura in estructuras %}
        <div class="col-1 m-2" {% if estructura.tipo.almacenaje == False %}onclick="window.location.href='{% url 'Estructura' estructura.id%}'"{% endif %}>
        <div><h4>{{ estructura.ubicacion }}</h4></div>
        <div><h6>{{ estructura.tipo }}</h6></div>

        {% if estructura.tipo.almacenaje %}
            Hola
            <div>
                {%  for pre in estructura.presentacionxubicacion_set.all%}
                   <h6>{{ pre.codigo }} - {{ presentacion.descripcion }}</h6>
                {% endfor %}
            </div>
        {% else %}
            {% if estructura.tipo.almacenaje and request.session.idpresentacion%}
                <a type="submit" role="button" class="button btn-sm" href="{% url 'Ubica' estructura.id %}">Seleccionar</a>
            {% endif %}
        {% endif %}


        </div>
    {% endfor %}
    </div>

{% endblock %}

templates/almacen/estructura2.html
{% extends '../base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block title %}Estructura{% endblock %}

{%  if request.session.descripcion != '' %}
    {% block breadcrumb %}
            <li class="breadcrumb-item">Asignacion</li>
            <li class="breadcrumb-item active">{{ request.session.descripcion }}</li>
    {% endblock %}
{% endif %}

{% block content %}
sssssssssssssssssssssssssssssssssssss
        <div class="row m-4">
            <h2>
            <a href="{% if  estructuras.first.padre.padre.id == None %} {% url 'EstructuraI'%} {% else %} {% url 'Estructura' estructuras.first.padre.padre.id|unlocalize%} {% endif %}">{{ estructuras.first.padre.ubicacion }} </a>
            </h2>
        </div>
    <div class="row m-4">


    {% for estructura in estructuras %}
        <div class="col-1 m-2" {% if estructura.tipo.almacenaje == False %}onclick="window.location.href='{% url 'Estructura' estructura.id%}'"{% endif %}>
        <div><h4>{{ estructura.ubicacion }}</h4></div>
        <div><h6>{{ estructura.tipo }}</h6></div>

        {% if estructura.tipo.almacenaje %}
            Hola
            <div>
                {%  for pre in estructura.presentacionxubicacion_set.all%}
                   <h6>{{ pre.codigo }} - {{ presentacion.descripcion }}</h6>
                {% endfor %}
            </div>
        {% else %}
            {% if estructura.tipo.almacenaje and request.session.idpresentacion%}
                <a type="submit" role="button" class="button btn-sm" href="{% url 'Ubica' estructura.id %}">Seleccionar</a>
            {% endif %}
        {% endif %}


        </div>
    {% endfor %}
    </div>

{% endblock %}

templates/almacen/recupera_transa.html
{% extends '../base.html' %}
{% load staticfiles %}


{% block content %}
<div class="row">
    <div class="col-4"></div>
            <div class="col-4">
                <h1>{{ tipo }}</h1>
            </div>
    </div>
</div>
<div class="row">
    <div class="col-4"></div>
        <div class="col-4">
            <form>
                 <input type="text"  name="transaid" id="idtransa" class="form-control tel" value="" />
                 <a class="btn btn-secondary btn-lg" href="#" onclick="recupera({% if tipo == 'Entradas' %}'1'{% else %}'0'{% endif %})">Importar</a>
           </form>
        </div>
</div>

<script>
    function recupera(vtipo){
        transa = $("#idtransa").val();
        if (transa != '') {
            console.log(transa);


            var url = 'http://' + location.hostname + ':' + location.port + '/almacen/recupera/' + transa + '/'+vtipo+'/';
            console.log(url);
            window.location.replace(url);
        } else {
            $("#idtransa").focus();
        }
    }



</script>
{% endblock content %}

templates/almacen/salida.html
{% extends '../base.html' %}
{% load staticfiles %}


{% block title %}Entrada{% endblock %}
{% block breadcrumb %}

        <li class="breadcrumb-item"><a href="{%   url 'Index' %}">Inicio</a></li>
        <li class="breadcrumb-item active">Salidas</li>
        <li class="breadcrumb-item active">Transaccion: {{ transaccion.transaccion }}</li>

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-1"></div>
            <div class="col-8">
                <h6>
                <span class="text text-info">Transaccion: </span><span>{{ transaccion.transaccion }}   </span>
                <span class="text-info">Fecha: </span><span>{{ transaccion.fecha }}   </span>
                </h6>
            </div>

    </div>

    <div class="row mt-2">
    <div class="col-1"></div>
    <div class="col-10">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Codigo</th>
                    <th>Descripcion</th>
                    <th>Cantidad</th>
                    <th>Costo</th>
                    <th>Importe</th>
                    <th>Subtotal</th>
                    <th>Impuestos</th>
                    <th>Total</th>
                    <th>Ubicacion</th>
                </tr>
            </thead>
            <tbody>
            {% for linea in transaccion.entradadetalle_set.all %}
                <tr>
                    <td>{{ linea.linea }}</td>
                    <td>{{ linea.presentacion.codigo }}</td>
                    <td>{{ linea.presentacion.descripcion }}</td>
                    <td>{{ linea.cantidad }}</td>
                    <td>{{ linea.costo }}</td>
                    <td>{{ linea.importe }}</td>
                    <td>{{ linea.subtotal }}</td>
                    <td>{{ linea.impuestos }}</td>
                    <td>{{ linea.total }}</td>
                    {% if linea.ubicacion != None%}
                        <td>
                            {{ linea.ubicacion }}
                        </td>
                    {% else %}
                    <td>
                      No existe
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{ transaccion.importe }}</td>
                    <td>{{ transaccion.subtotal }}</td>
                    <td>{{ transaccion.impuestos }}</td>
                    <td>{{ transaccion.total }}</td>

                </tr>
            </tfoot>
        </table>

     <a class="btn btn-primary btn-sm" role="button"  href="#"  onclick="window.print()">Imprimir</a>

     <a class="btn btn-dark btn-sm" role="button"  href="{% url 'Salida' %}" >Otra salida </a>
     <a class="btn btn-dark btn-sm" role="button"  href="{% url 'Index' %}" >Salir </a>

    </div>

    </div>



{% endblock %}

templates/almacen/unidadesxpre_dropdown_2_options.html
{% if unds.count > 1 %}
<option value="">---------</option>
{% endif %}
{% for und in unds %}
<option value="{{ und.unidad.pk }}">{{ und.unidad }}</option>
{% endfor %}